FROM rabbitmq:3.9.21-management

# COPY ./data /var/lib/rabbitmq/mnesia

RUN chmod -Rf 777 /var/lib/rabbitmq

# COPY --chown=rabbitmq:rabbitmq ./rabbitmq-env.conf /etc/rabbitmq/rabbitmq-env.conf

# CMD chmod 700 /var/lib/rabbitmq